theme: jekyll-theme-minimal
title: filesmuggler's homepage
description: Bookmark this to keep an eye on my project updates!

relative_links:
  enabled: true
  collections: true
include:
 - ros4rpi.md
 - imu4rpi.md
